[licenses]
# See <https://spdx.org/licenses/> for list of possible licenses
allow = [
  "Apache-2.0",
  "BSD-3-Clause",
  "MIT",
  "MPL-2.0",
  "Zlib",
  "Unicode-3.0",
  "ISC",
  "CDLA-Permissive-2.0",
  "OpenSSL",
]
private = { ignore = true }
confidence-threshold = 0.8

[[licenses.clarify]]
name = "ring"
version = "0.17.8"
expression = "Apache-2.0 AND ISC AND MIT AND OpenSSL"
license-files = [{ path = "LICENSE", hash = 0xbd0eed23 }]
