[server]
address = '0.0.0.0:3001'
log_level = 'info'
url = 'https://api.domain.com'

[database]
connection_string = 'postgresql://user:pass@host:port/db'

[blockfrost]
project_id = 'preview_BLOCKFROST_PROJECT_ID'
nft_asset = '4213fc3eac8c781ac85514dd1de9aaabcd5a3a81cc2df4f413b9b295'

[hydra]
cardano_signing_key = "/home/mw/.config/blockfrost-platform/hydra/tmp_their_keys/payment.sk"
