[package]
name = "build-utils"
version.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
toml.workspace = true
bzip2 = "0.4.3"
tar = "0.4.38"
zip = "0.6.6"
reqwest.workspace = true

[lints]
workspace = true
