[package]
name = "blockfrost-platform-build-utils"
version.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
toml.workspace = true
bzip2 = "0.6.1"
tar = "0.4.44"
zip = "8.1.0"
reqwest.workspace = true

[lints]
workspace = true
