[package]
name = "blockfrost-platform-api-provider"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
blockfrost-openapi.workspace = true

[lints]
workspace = true
